### ISSUE TITLE
Broken with pytest v8

### ISSUE THREAD

**Issue by dm-ackerman** [modal-labs/pytest-markdown-docs#18]
This doesn't work with the recent pytest v8. I saw there is a pull request with a tentative fix: https://github.com/modal-labs/pytest-markdown-docs/pull/17

Can this be verified and added as a new version that can be pulled via pip?

**Comment by ekzhang** [comment]
Thanks! I noticed recently that it broke with pytest v8 but didn't notice the fix.

**Comment by dm-ackerman** [comment]
Thanks for looking at this! I didn't make the fix and don't know if it still runs correctly, but I can confirm that it runs without error on my code with pytest v8

**Comment by freider** [comment]
Fixed in the just released v0.5.0
